/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2_edd;

/**
 *
 * @author simon
 */
public class VentanaMain extends javax.swing.JFrame {
    private String fileName;
    /**
     * Creates new form VentanaMain
     */
    public VentanaMain(String fileName) {
        this.fileName = fileName;
        initComponents();
        textArea.setEditable(false);
        if (fileName != null){
            handleJsonFile(fileName);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        showTree = new javax.swing.JButton();
        verRegistro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nameList = new javax.swing.JList<>();
        nameSearch = new javax.swing.JButton();
        mostrarAntepasados = new javax.swing.JButton();
        titleSearch = new javax.swing.JButton();
        generationList = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        nameTextField = new javax.swing.JTextField();
        titleTextField = new javax.swing.JTextField();
        BaratheonLabel = new javax.swing.JLabel();
        TargaryenLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Reemplazar Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 30));

        showTree.setText("Mostrar Arbol");
        showTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTreeActionPerformed(evt);
            }
        });
        jPanel1.add(showTree, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        verRegistro.setText("Ver Registro");
        verRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(verRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        nameList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Nodo 1", "Nodo 2", "Nodo 3", "Nodo 4", "Nodo 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(nameList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 240, 350));

        nameSearch.setText("Buscar por Nombre");
        nameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSearchActionPerformed(evt);
            }
        });
        jPanel1.add(nameSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        mostrarAntepasados.setText("Mostrar Antepasados");
        mostrarAntepasados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAntepasadosActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarAntepasados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        titleSearch.setText("Buscar por Titulo");
        jPanel1.add(titleSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        generationList.setText("Lista de Integrantes de una Generacion");
        jPanel1.add(generationList, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane2.setViewportView(textArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 240, 90));
        jPanel1.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 200, -1));
        jPanel1.add(titleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 200, -1));

        BaratheonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_edd/game-of-thrones-house-baratheon (1).jpg"))); // NOI18N
        jPanel1.add(BaratheonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        TargaryenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_edd/house-targaryen-game-of-thrones (1).jpg"))); // NOI18N
        jPanel1.add(TargaryenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaInicio v1 = new VentanaInicio();
        this.dispose();
        v1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mostrarAntepasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarAntepasadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarAntepasadosActionPerformed

    private void showTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTreeActionPerformed
        Tree tree = new Tree();
        tree.loadNamesFromJSON(fileName);
        Grafo grafo = new Grafo();
        grafo.buildFromTree(tree);
        grafo.displayGraph();
    }//GEN-LAST:event_showTreeActionPerformed

    private void nameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameSearchActionPerformed

    private void verRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verRegistroActionPerformed

    public void handleJsonFile(String fileName){
        TargaryenLabel.setVisible(false);
        BaratheonLabel.setVisible(false);
        if (fileName.contains("Targaryen.json")){
            TargaryenLabel.setVisible(true);
        }else if (fileName.contains("Baratheon.json")){
            BaratheonLabel.setVisible(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMain(FileStorage.getInstance().getFilename()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BaratheonLabel;
    private javax.swing.JLabel TargaryenLabel;
    private javax.swing.JButton generationList;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mostrarAntepasados;
    private javax.swing.JList<String> nameList;
    private javax.swing.JButton nameSearch;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton showTree;
    private javax.swing.JTextArea textArea;
    private javax.swing.JButton titleSearch;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JButton verRegistro;
    // End of variables declaration//GEN-END:variables
}